# Generated by Django 4.1.6 on 2023-02-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('hours', models.PositiveIntegerField(default=2)),
                ('course_image', models.ImageField(upload_to='course/')),
            ],
        ),
    ]
